import type { Metadata } from 'next';
import Link from 'next/link';
import { breadcrumbSchema, JsonLd } from '@/lib/seo';
import { getSiteContent } from '@/lib/supabase';

const title = 'About The Snohomish';
const description = 'Meet The Snohomish, a Nairobi wines, spirits and beverage retail and distribution group serving individuals and businesses.';
export const metadata: Metadata = { title, description, alternates: { canonical: '/about' }, openGraph: { title, description, url: '/about', type: 'website' }, twitter: { card: 'summary', title, description } };
export default async function AboutPage() { const content=await getSiteContent(); return <main className="bg-[#f5f4f0] px-5 py-16"><JsonLd data={[{'@context':'https://schema.org','@type':'AboutPage',name:title,description,url:'/about'},breadcrumbSchema([{name:'Home',url:'/'},{name:'About',url:'/about'}])]}/><article className="mx-auto max-w-5xl rounded-3xl bg-white p-7 shadow-card sm:p-12"><p className="eyebrow dark">Distribution · Retail · Wholesale</p><h1 className="mt-3 text-5xl font-black tracking-tight text-[#0d0d0d]">Built to serve Nairobi.</h1><div className="mt-7 space-y-5 text-lg leading-8 text-neutral-700"><p>{content.about||'The Snohomish is a Nairobi-based wines, spirits and beverage distribution and retail group serving individual customers and businesses. Through Mautamu, The Snohomish and Three Amigos retail outlets, our online store and wholesale operations, we serve customers ranging from individual shoppers to bars, restaurants, retailers, supermarkets, events and corporate organisations.'}</p><p id="mega-drive-through" className="rounded-2xl bg-[#191919] p-6 font-bold text-white">An upcoming <span className="text-[#fff500]">Mega Drive-Through</span> is currently under development as part of our growing retail and distribution network.</p></div><div className="mt-8 flex gap-5"><Link href="/shop" className="font-black text-neutral-900 underline decoration-[#fff500] decoration-4">Shop drinks</Link><Link href="/contact" className="font-black text-neutral-900 underline decoration-[#fff500] decoration-4">Talk to our team</Link></div></article></main>; }
