-- Additive schema synchronization for the copied The Snohomish application.
-- This migration never drops tables or rows and is safe to rerun.
begin;
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;

create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, parent_id uuid, icon text, image_url text, description text, color text, seo_title text, seo_description text, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.categories add column if not exists parent_id uuid, add column if not exists icon text, add column if not exists image_url text, add column if not exists description text, add column if not exists color text, add column if not exists seo_title text, add column if not exists seo_description text, add column if not exists sort_order integer not null default 0, add column if not exists is_active boolean not null default true, add column if not exists created_at timestamptz not null default now(), add column if not exists updated_at timestamptz not null default now();
create table if not exists public.brands (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, country text, logo_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.admin_users (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, email text not null unique, role text not null default 'admin', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), category_id uuid, brand_id uuid, name text not null, slug text not null unique, description text, short_description text, price numeric(12,2) not null default 0, old_price numeric(12,2), stock integer not null default 0, image_url text, gallery_urls text[] not null default '{}', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.products add column if not exists tasting_notes text, add column if not exists pairing_suggestions text, add column if not exists country text, add column if not exists bottle_size text, add column if not exists grape_variety text, add column if not exists wine_type text, add column if not exists sweetness text, add column if not exists whisky_type text, add column if not exists age_statement text, add column if not exists beer_type text, add column if not exists pack_size text, add column if not exists product_format text, add column if not exists gin_style text, add column if not exists flavour text, add column if not exists abv numeric(5,2), add column if not exists sku text, add column if not exists barcode text, add column if not exists currency text not null default 'KES', add column if not exists low_stock_threshold integer not null default 5, add column if not exists track_inventory boolean not null default true, add column if not exists metadata jsonb not null default '{}'::jsonb, add column if not exists seo_title text, add column if not exists seo_description text, add column if not exists is_featured boolean not null default false, add column if not exists is_top_seller boolean not null default false, add column if not exists is_new_arrival boolean not null default false, add column if not exists sort_order integer not null default 0, add column if not exists discount_starts_at timestamptz, add column if not exists discount_ends_at timestamptz, add column if not exists discount_label text;

create table if not exists public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null, name text not null, sku text unique, option_values jsonb not null default '{}'::jsonb, price numeric(12,2) not null default 0, old_price numeric(12,2), stock integer not null default 0, low_stock_threshold integer not null default 5, image_url text, is_active boolean not null default true, sort_order integer not null default 0, discount_starts_at timestamptz, discount_ends_at timestamptz, discount_label text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), user_id uuid unique references auth.users(id) on delete cascade, full_name text not null, phone text, email text, loyalty_points integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.delivery_locations (id uuid primary key default gen_random_uuid(), customer_id uuid, label text, address text not null, apartment text, building text, delivery_instructions text, latitude numeric(10,7), longitude numeric(10,7), place_id text, place_name text, delivery_fee numeric(10,2) not null default 0, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid, order_number text, customer_name text, customer_email text, customer_phone text, delivery_location_id uuid, delivery_address text, gps_lat numeric(10,7), gps_lng numeric(10,7), delivery_place_id text, delivery_place_name text, delivery_location_verified boolean not null default false, delivery_instructions text, status text not null default 'pending', payment_method text not null default 'mpesa', payment_status text not null default 'pending', payment_reference text, subtotal numeric(12,2) not null default 0, delivery_fee numeric(10,2) not null default 0, discount_total numeric(10,2) not null default 0, total numeric(12,2) not null default 0, checkout_token uuid not null default gen_random_uuid(), gift_note text, admin_notes text, rider_name text, rider_phone text, tracking_url text, accepted_at timestamptz, processing_at timestamptz, dispatched_at timestamptz, delivered_at timestamptz, cancelled_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.orders add column if not exists order_number text, add column if not exists customer_name text, add column if not exists customer_email text, add column if not exists customer_phone text, add column if not exists checkout_token uuid default gen_random_uuid(), add column if not exists delivery_place_id text, add column if not exists delivery_place_name text, add column if not exists delivery_location_verified boolean not null default false, add column if not exists delivery_instructions text, add column if not exists rider_name text, add column if not exists rider_phone text, add column if not exists tracking_url text, add column if not exists accepted_at timestamptz, add column if not exists processing_at timestamptz, add column if not exists dispatched_at timestamptz, add column if not exists delivered_at timestamptz, add column if not exists cancelled_at timestamptz;
update public.orders set order_number='SNO-'||upper(substr(replace(id::text,'-',''),1,12)) where order_number is null;
create unique index if not exists orders_order_number_key on public.orders(order_number) where order_number is not null;
create unique index if not exists orders_checkout_token_key on public.orders(checkout_token) where checkout_token is not null;

create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null, product_id uuid, variant_id uuid, product_name text not null, quantity integer not null, unit_price numeric(12,2) not null, line_total numeric(12,2) not null, created_at timestamptz not null default now());
create table if not exists public.homepage_banners (id uuid primary key default gen_random_uuid(), title text not null, subtitle text, image_url text, mobile_image_url text, badge_text text, button_label text, button_text text, button_url text, sort_order integer not null default 0, is_active boolean not null default true, starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.homepage_banners add column if not exists subtitle text, add column if not exists image_url text, add column if not exists mobile_image_url text, add column if not exists badge_text text, add column if not exists button_label text, add column if not exists button_text text, add column if not exists button_url text, add column if not exists sort_order integer not null default 0, add column if not exists is_active boolean not null default true, add column if not exists starts_at timestamptz, add column if not exists ends_at timestamptz, add column if not exists created_at timestamptz not null default now(), add column if not exists updated_at timestamptz not null default now();
create table if not exists public.homepage_product_sections (id uuid primary key default gen_random_uuid(), heading text not null, category_id uuid, product_ids uuid[] not null default '{}', use_best_sellers boolean not null default false, item_limit integer not null default 8, sort_order integer not null default 0, rotation_enabled boolean not null default false, rotation_seconds integer not null default 6, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.promotions (id uuid primary key default gen_random_uuid(), title text not null, code text unique, description text, discount_type text not null default 'fixed', discount_value numeric(10,2) not null default 0, image_url text, badge_text text, button_label text, button_url text, sort_order integer not null default 0, starts_at timestamptz, ends_at timestamptz, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.store_settings (key text primary key, value jsonb not null default '{}'::jsonb, description text, is_public boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.delivery_settings (id uuid primary key default gen_random_uuid(), name text not null unique, min_distance_km numeric(8,2) not null default 0, max_distance_km numeric(8,2), fee numeric(10,2) not null default 0, estimated_minutes_min integer not null default 10, estimated_minutes_max integer not null default 50, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table if not exists public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null, provider text not null, status text not null default 'pending', amount numeric(12,2) not null, phone_number text, merchant_request_id text unique, checkout_request_id text unique, receipt_number text unique, provider_result_code text, provider_result_desc text, transaction_at timestamptz, raw_callback jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.admin_notifications (id uuid primary key default gen_random_uuid(), order_id uuid, kind text not null, title text not null, body text not null, is_read boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.notification_deliveries (id uuid primary key default gen_random_uuid(), order_id uuid, channel text not null, recipient text not null, event_key text not null, status text not null default 'pending', provider_message_id text, error_message text, attempts integer not null default 0, created_at timestamptz not null default now(), sent_at timestamptz, unique(order_id,channel,recipient,event_key));
create table if not exists public.order_notifications (id uuid primary key default gen_random_uuid(), order_id uuid not null, channel text not null, recipient text not null, event_key text not null, status text not null default 'pending', error_message text, created_at timestamptz not null default now(), unique(order_id,channel,recipient,event_key));
create table if not exists public.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null, from_status text, to_status text not null, note text, changed_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.reward_accounts (id uuid primary key default gen_random_uuid(), customer_id uuid not null unique, points_balance integer not null default 0, lifetime_points integer not null default 0, points_redeemed integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.reward_transactions (id uuid primary key default gen_random_uuid(), reward_account_id uuid not null, order_id uuid, transaction_type text not null, points integer not null, description text, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.reward_redemptions (id uuid primary key default gen_random_uuid(), reward_account_id uuid not null, points integer not null, reward_name text not null, status text not null default 'pending', redeemed_at timestamptz not null default now(), used_at timestamptz);
create table if not exists public.product_reviews (id uuid primary key default gen_random_uuid(), customer_id uuid not null, order_item_id uuid not null unique, product_id uuid, rating integer not null, review text, is_published boolean not null default false, created_at timestamptz not null default now());

-- Add discoverable foreign keys only when an equivalent relationship is absent.
do $$ declare r record; begin
 for r in select * from (values
 ('categories','parent_id','categories','id','categories_parent_id_fkey','SET NULL'),('products','category_id','categories','id','products_category_id_fkey','SET NULL'),('products','brand_id','brands','id','products_brand_id_fkey','SET NULL'),('product_variants','product_id','products','id','product_variants_product_id_fkey','CASCADE'),('delivery_locations','customer_id','customers','id','delivery_locations_customer_id_fkey','CASCADE'),('orders','customer_id','customers','id','orders_customer_id_fkey','SET NULL'),('orders','delivery_location_id','delivery_locations','id','orders_delivery_location_id_fkey','SET NULL'),('order_items','order_id','orders','id','order_items_order_id_fkey','CASCADE'),('order_items','product_id','products','id','order_items_product_id_fkey','SET NULL'),('order_items','variant_id','product_variants','id','order_items_variant_id_fkey','SET NULL'),('homepage_product_sections','category_id','categories','id','homepage_product_sections_category_id_fkey','SET NULL'),('payments','order_id','orders','id','payments_order_id_fkey','CASCADE'),('admin_notifications','order_id','orders','id','admin_notifications_order_id_fkey','CASCADE'),('notification_deliveries','order_id','orders','id','notification_deliveries_order_id_fkey','CASCADE'),('order_notifications','order_id','orders','id','order_notifications_order_id_fkey','CASCADE'),('order_status_history','order_id','orders','id','order_status_history_order_id_fkey','CASCADE'),('reward_accounts','customer_id','customers','id','reward_accounts_customer_id_fkey','CASCADE'),('reward_transactions','reward_account_id','reward_accounts','id','reward_transactions_reward_account_id_fkey','CASCADE'),('reward_transactions','order_id','orders','id','reward_transactions_order_id_fkey','SET NULL'),('reward_redemptions','reward_account_id','reward_accounts','id','reward_redemptions_reward_account_id_fkey','CASCADE'),('product_reviews','customer_id','customers','id','product_reviews_customer_id_fkey','CASCADE'),('product_reviews','order_item_id','order_items','id','product_reviews_order_item_id_fkey','CASCADE'),('product_reviews','product_id','products','id','product_reviews_product_id_fkey','SET NULL')) as x(t,c,rt,rc,n,action)
 loop if not exists(select 1 from pg_constraint where conrelid=('public.'||r.t)::regclass and contype='f' and conkey=array[(select attnum from pg_attribute where attrelid=('public.'||r.t)::regclass and attname=r.c)]) then execute format('alter table public.%I add constraint %I foreign key (%I) references public.%I(%I) on delete %s',r.t,r.n,r.c,r.rt,r.rc,r.action); end if; end loop;
end $$;

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_active_sort_idx on public.products(is_active,sort_order,created_at desc);
create index if not exists variants_product_idx on public.product_variants(product_id,is_active,sort_order);
create index if not exists orders_customer_created_idx on public.orders(customer_id,created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists homepage_product_sections_active_sort_idx on public.homepage_product_sections(is_active,sort_order);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.admin_users where user_id=auth.uid() and is_active) $$;
revoke all on function public.is_admin() from public; grant execute on function public.is_admin() to anon,authenticated;

-- RLS: public catalogue reads, admin writes; customer operational rows remain owner-only.
do $$ declare t text; begin foreach t in array array['admin_users','categories','brands','products','product_variants','homepage_banners','homepage_product_sections','promotions','store_settings','delivery_settings','customers','delivery_locations','orders','order_items','payments','admin_notifications','notification_deliveries','order_notifications','order_status_history','reward_accounts','reward_transactions','reward_redemptions','product_reviews'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
drop policy if exists "Public read active categories sync" on public.categories; create policy "Public read active categories sync" on public.categories for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read active brands sync" on public.brands; create policy "Public read active brands sync" on public.brands for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read active products sync" on public.products; create policy "Public read active products sync" on public.products for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read active variants sync" on public.product_variants; create policy "Public read active variants sync" on public.product_variants for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read active banners sync" on public.homepage_banners; create policy "Public read active banners sync" on public.homepage_banners for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read active promotions sync" on public.promotions; create policy "Public read active promotions sync" on public.promotions for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read delivery settings sync" on public.delivery_settings; create policy "Public read delivery settings sync" on public.delivery_settings for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Public read store settings sync" on public.store_settings; create policy "Public read store settings sync" on public.store_settings for select to anon,authenticated using(is_public or public.is_admin());
drop policy if exists "Public read active homepage product sections" on public.homepage_product_sections; create policy "Public read active homepage product sections" on public.homepage_product_sections for select to anon,authenticated using(is_active or public.is_admin());
drop policy if exists "Admin write homepage product sections" on public.homepage_product_sections; create policy "Admin write homepage product sections" on public.homepage_product_sections for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admin write products sync" on public.products; create policy "Admin write products sync" on public.products for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admin write categories sync" on public.categories; create policy "Admin write categories sync" on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit) values ('product-images','product-images',true,10485760),('category-images','category-images',true,10485760),('banner-images','banner-images',true,10485760) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit;
drop policy if exists "Public read Snohomish images" on storage.objects; create policy "Public read Snohomish images" on storage.objects for select using(bucket_id in ('product-images','category-images','banner-images'));
drop policy if exists "Admins manage Snohomish images" on storage.objects; create policy "Admins manage Snohomish images" on storage.objects for all to authenticated using(bucket_id in ('product-images','category-images','banner-images') and public.is_admin()) with check(bucket_id in ('product-images','category-images','banner-images') and public.is_admin());

notify pgrst,'reload schema';
commit;
